spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include:
      - gpt
      - jwt
      - oauth