spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: ture
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include:
      - gpt
      - jwt
jwt:
  issuer: kiki
  secret_key: kikisecret